version: "3.4"
services:
    api:
        container_name: webApi
        build: ./Api
        environment:
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=443
            - ASPNETCORE_Kestrel__Certificates__Default__Password=g-BPGBsgKqsV.v!@jT2f
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/api.pfx
        volumes:
            - C:\certs\service-worker\:C:\https\
        networks:
            bridge:
                ipv4_address: 172.18.0.10
networks:
    bridge:
        driver: nat
        ipam:
            config:
                - subnet: 172.18.0.0/16