version: "3.4"
services:
    api:
        build: ./api
        container_name: webapi
        ports:
            - 80
            - 443
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=theking
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/webapi.crt
        volumes:
            - ./api/ssl:C:\https:ro
        restart: unless-stopped
        networks:
            bridge:
                ipv4_address: 172.18.0.10
    spa:
        container_name: site
        build: ./site
        networks:
            bridge:
                ipv4_address: 172.18.0.11
networks:
    bridge:
        driver: nat
        ipam:
            config:
                - subnet: 172.18.0.0/16